###List all messages
GET http://localhost:3000/message/

### List particular message
GET http://localhost:3000/message/840

###create a new message
POST http://localhost:3000/message
Content-Type: application/json

{
    "content":"used better approch using DI"
}



